// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdnrdeypnybhyjakepfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbnJkZXlwbnliaHlqYWtlcGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDMxODQsImV4cCI6MjA3MjU3OTE4NH0.SOxjtO8gi6Qsck-eziermnD5WaM_UbHDuDudLAK22AE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});